### ISSUE TITLE
Error: Can't set headers after they are sent when yarn start

### ISSUE THREAD

**Issue by pmg1989** [CodementorIO/nextjs-redux-starter#2]
code is Very nice，but there are some bugs,
![image](https://user-images.githubusercontent.com/13361827/37085603-6c894056-2230-11e8-8dd4-6943bd12922d.png)

**Comment by IanWang** [comment]
which page? could you help me to reproduce?

**Comment by pmg1989** [comment]
i think i found it.[Getting error for next 5.0.0 but not 4.3.0.](https://github.com/zeit/next.js/issues/3890)

**Comment by minhquankq** [comment]
The same for next 6.0.0.

**Comment by ianwang** [comment]
https://github.com/zeit/next.js/issues/3890#issuecomment-450598741
