### ISSUE TITLE
Server keeps on crashing

### ISSUE THREAD

**Issue by wakahiu** [CodementorIO/nextjs-redux-starter#30]
<--- Last few GCs --->

[16807:0x10286a000]   107007 ms: Scavenge 2034.5 (2049.3) -> 2031.6 (2049.8) MB, 7.7 / 0.0 ms  (average mu = 0.149, current mu = 0.096) allocation failure
[16807:0x10286a000]   107033 ms: Scavenge 2035.0 (2049.8) -> 2032.0 (2050.1) MB, 6.5 / 0.0 ms  (average mu = 0.149, current mu = 0.096) allocation failure
[16807:0x10286a000]   107067 ms: Scavenge 2035.5 (2050.1) -> 2032.5 (2058.6) MB, 7.9 / 0.0 ms  (average mu = 0.149, current mu = 0.096) allocation failure

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1000768af node::Abort() [/usr/local/bin/node]
 2: 0x100076a33 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10016a827 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10016a7bc v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x100337ce5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x100338dd3 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 7: 0x1003365b3 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10033426f v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x10033ba09 v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
10: 0x100349dff v8::internal::IncrementalMarkingJob::Task::RunInternal() [/usr/local/bin/node]
11: 0x1000c8d64 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/usr/local/bin/node]
12: 0x1000c81b0 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/local/bin/node]
13: 0x10086838c uv__async_io [/usr/local/bin/node]
14: 0x1008788ed uv__io_poll [/usr/local/bin/node]
15: 0x100868816 uv_run [/usr/local/bin/node]
16: 0x1000ac577 node::NodeMainInstance::Run() [/usr/local/bin/node]
17: 0x100056ccc node::Start(int, char**) [/usr/local/bin/node]
18: 0x7fff5f6513d5 start [/usr/lib/system/libdyld.dylib]
19: 0x2

**Comment by ianwang** [comment]
Couldn't reproduce. It doesn't seem to be related to the starter setup. Found something similar https://github.com/zeit/next.js/issues/9442
