### ISSUE TITLE
TypeError: Cannot read property 'renderStatic' of undefined

### ISSUE THREAD

**Issue by pluwum** [CodementorIO/nextjs-redux-starter#42]
I am getting this error when i pull and try to set up locally.

`TypeError: Cannot read property 'renderStatic' of undefined
    at Function.getInitialProps (/Users/luwumalvinpatrick/Projects/perf-eval/client/.next/server/static/development/pages/_document.js:1092:69)`

I am guessing this has something to do with the  latest helment update introduced by #41 

**Solution**
in _document.js. i've changed 
import Helmet from 'react-helmet' into import { Helmet } from 'react-helmet'

**Comment by ianwang** [comment]
thanks! should be fixed now :)
