### ISSUE TITLE
next-redux-wrapper

### ISSUE THREAD

**Issue by muhilham** [CodementorIO/nextjs-redux-starter#7]
I cannot use next-redux-wrapper version 2.0.0. 
BTW this is very simple boilerplate. Love it

**Comment by ianwang** [comment]
I think there's a breaking change from the current version (`1.3.5`). will take a look when I have some free time. Feel free to send a PR 😄

**Comment by balge** [comment]
when i set up next-redux-wrapper @v2.x,and set store at _app.js with provide ,the program cat not run

**Comment by ianwang** [comment]
https://github.com/CodementorIO/nextjs-redux-starter/commit/16620936d6e6cebb63676ced89fbb5ac2059b9d2
