### ISSUE TITLE
_app.js

### ISSUE THREAD

**Issue by newyoung21** [CodementorIO/nextjs-redux-starter#8]
## Can you create multiple _app.js files, each page has its own separate store

**Comment by ianwang** [comment]
no, you can only have one `_app.js`

**Comment by newyoung21** [comment]
@ianwang  
I have a question. next.js is a multi-page project, and all pages share a store. Will this make each output file too large

**Comment by ianwang** [comment]
@newyoung21 
try https://github.com/zeit/next.js/tree/canary/examples/with-redux-code-splitting
