### ISSUE TITLE
Implementing next/error

### ISSUE THREAD

**Issue by nbpetts** [CodementorIO/nextjs-redux-starter#9]
We are using your starter to build a website backed by Contentful. We cannot get the Next error page to work, though. 

We created an error page and added an error page:  `import React from 'react'

export default class Error extends React.Component {
  static getInitialProps({ res, err }) {
    const statusCode = res ? res.statusCode : err ? err.statusCode : null;
    return { statusCode }
  }

  render() {
    return (
      <p>
        {this.props.statusCode
          ? `An error ${this.props.statusCode} occurred on server`
          : 'An error occurred on client'}
      </p>
    )
  }
}`

but we only get a plain text error reading "Internal Server Error"
I suspect this is express not finding a route, but I am not sure what to do to give it a catch all. Here is my routes file and my server:

routes.js 
`const nextRoutes = require('next-routes');

const routes = (module.exports = nextRoutes());

const APP_ROUTES = [
  {
    page: 'index',
    pattern: '/',
  },

  {
    page: 'creators',
    pattern: '/creators',
  },
  {
    page: 'product',
    pattern: '/product',
  },
  {
    page: 'plans',
    pattern: '/plans',
  },

  {
    page: 'customers',
    pattern: '/customers',
  },

  {
    page: 'demo',
    pattern: '/demo',
  },

  // ABout
  {
    page: 'careers',
    pattern: '/careers',
  },
  {
    page: 'about',
    pattern: '/about-us',
  },
  {
    page: 'contact',
    pattern: '/contact-us',
  },
  {
    page: 'team',
    pattern: '/team',
  },
  {
    page: 'terms',
    pattern: '/terms',
  },
  {
    page: 'privacy',
    pattern: '/privacy',
  },

  // Blog
  {
    page: 'blog',
    pattern: '/blog',
  },
  {
    page: 'article',
    pattern: '/blog/:slug',
  },

  // Resources
  {
    page: 'resources',
    pattern: '/resources',
  },
  {
    page: 'resourceCategory',
    pattern: '/resources/:category',
  },
];

APP_ROUTES.forEach(route => routes.add(route));
`
Server:
`
const path = require('path');
const express = require('express');
const compression = require('compression');
const next = require('next');
const helmet = require('helmet');
const auth = require('http-auth');

const routes = require('../routes');

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });

const handler = routes.getRequestHandler(app);

const basic = auth.basic({
  realm: '###ClientName###',
  file: `${__dirname}/.htpasswd`,
});

app.prepare().then(() => {
  const server = express();

  server.use(helmet());
  server.use(compression());
  if (process.env.NODE_ENV === 'staging') {
    server.use(auth.connect(basic));
  }

  const staticPath = path.join(__dirname, '../static');
  server.use(
    '/static',
    express.static(staticPath, {
      maxAge: '30d',
      immutable: true,
    }),
  );

  server.get('*', (req, res) => handler(req, res));

  server.listen(port, () => {
    console.log(`> Ready on http://localhost:${port}`);
  });
});
`

**Comment by ianwang** [comment]
I'm not sure if this is related to the starter. Are you following [the instruction](https://github.com/zeit/next.js#custom-error-handling)? notice that it would only work on production.

> The pages/_error.js component is only used in production. In development you get an error with call stack to know where the error originated from.
